name: Data-Update

on: 
  schedule:
  - cron: "*/20 * * * *"

jobs:
  update-data:
    name: Update data from remote
    environment: secrests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update remote data
        run: |
          git remote add upstream https://github.com/opencovid19-fr/data 
          git pull upstream master
      - name: new Branch
        uses: actions/checkout@v2
        with:
         ref: data
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
      - name: Run script
        run: python filter_csv.py
          python filter_csv_consolidate.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GH_PAT }}
            commit-message: Update DATA (auto)
            title: Update DATA (auto)
#       - name: pull request
#         uses: gorillio/github-action-sync@master
#         with:
#           upstream: opencovid19-fr/data
#           upstream_branch: master
#           branch: master
#           pr_labels: upstream
#         env: 
#           GITHUB_TOKEN: ${secrets.GH_PAT}
#           GITBOT_EMAIL: k.kobiela@samsung.com
#           DRY_RUN: false  
